name: CI

on:
  push:
    branches: [ trunk, try/phpunit-tests ]
  pull_request:
    branches: [ trunk ]

  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2

      - name: Install NodeJS
        uses: actions/setup-node@eeb10cff27034e7acf239c5d29f62154018672fd # v3.3.0
        with:
            node-version-file: '.nvmrc'
            cache: yarn

      - name: Install dependencies & setup configs
        run: |
              yarn setup:tools

      - name: Install dependencies
        run: |
            yarn
            composer install
            yarn build
            yarn wp-env start

      - name: Run PHP unit tests
        run: |
            yarn test:php
