#!/usr/bin/env php
<?php

namespace WordCamp\Git_Hooks\Pre_Push;
use Exception;


/*
 * The functionality from `pre-commit` should probably be moved here, because `pre-push` is a better workflow,
 * and PHP is a much better scripting language.
 */

$color_green = "\033[32m";
$color_red   = "\033[31m";
$color_reset = "\033[m";

main();


function main() {
	global $color_green, $color_red, $color_reset;

	$current_branch = trim( shell_exec( "/usr/bin/git rev-parse --abbrev-ref HEAD 2>&1" ) );

	/*
	 * Only run this hook on finished commits that are ready for production. It should be skipped during
	 * the development process, in order to keep a frictionless workflow.
	 */
	if ( 'production' !== $current_branch ) {
		exit( 0 );
	}

	/*
	 * Other workspaces can be added once they pass the linters on the `production` branch, or this has the
	 * ability to run on only changed lines.
	 */
	$workspaces = array(
		'wordcamp-blocks'           => 'mu-plugins/blocks',
		'virtual-embeds'            => 'mu-plugins/virtual-embeds',
		'wordcamp-speaker-feedback' => 'plugins/wordcamp-speaker-feedback',
	);

	$changed_files = shell_exec( '/usr/bin/git diff origin/production --name-only' );

	try {
		php_test( $changed_files );
		js_css_lint( $workspaces, $changed_files );

	} catch( Exception $exception ) {
		echo "\n\n" . $exception->getMessage() . "\n\n";
		echo "{$color_red}Please fix the errors above, or intentionally bypass this with `git push --no-verify`.{$color_reset} \n\n";

		exit( 1 );
	}

	echo "\n\n{$color_green}All pre-push tests passed.{$color_reset}\n\n";
	exit( 0 );
}

/**
 * Run the PHP test suites.
 *
 * @param string $changed_files
 *
 * @throws Exception if tests fail.
 */
function php_test( $changed_files ) {
	if ( false === strpos( $changed_files, '.php' ) ) {
		return;
	}

	echo "\nRunning PHP tests... ";

	exec( 'composer run test 2>&1', $test_output, $exec_exit_status );

	if ( 0 !== $exec_exit_status ) {
		throw new Exception( implode( "\n", $test_output ) );
	}
}

/**
 * Lint JavaScript and CSS files.
 *
 * @param array  $workspaces
 * @param string $changed_files
 *
 * @throws Exception if tests fail.
 */
function js_css_lint( $workspaces, $changed_files ) {
	foreach ( $workspaces as $name => $path ) {
		if ( false !== strpos( $changed_files, $path ) ) {
			echo "\nLinting $name workspace... ";

			exec( 'yarn --silent workspace ' . $name . ' lint:js 2>&1', $lint_js_output, $exec_exit_status );

			if ( $exec_exit_status ) {
				throw new Exception( implode( "\n", $lint_js_output ) );
			}

			exec( 'yarn --silent workspace ' . $name . ' lint:css 2>&1', $lint_css_output, $exec_exit_status );

			if ( $exec_exit_status ) {
				throw new Exception( implode( "\n", $lint_css_output ) );
			}
		}
	}
}
