FROM mariadb:lts

RUN apt-get update \
    && apt-get install -y \
        nano \
        vim

# Set default password
ENV MARIADB_ROOT_PASSWORD=mysql
ENV MARIADB_DATABASE=wordcamp_dev

ADD data/wordcamp_dev.sql /docker-entrypoint-initdb.d/data.sql

EXPOSE 3306
