FROM mysql:5.7-debian

RUN apt-get update \
    && apt-get install -y \
        nano \
        vim

# Set default password
ENV MYSQL_ROOT_PASSWORD=mysql
ENV MYSQL_DATABASE=wordcamp_dev

ADD data/wordcamp_dev.sql /docker-entrypoint-initdb.d/data.sql

EXPOSE 3306
