name: Static Analysis (Linting)

# Run on any changes in public_html
on:
  pull_request:
    paths:
    - public_html/**
  push:
    branches: [production]
    paths:
    - public_html/**

jobs:
  check:
    name: All

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Use Node.js 12.x
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12.x

    - name: composer install
      run: |
        composer install

    - name: yarn install and build
      run: |
        yarn
        yarn workspaces run build

    - name: Lint JavaScript and Styles
      run: |
        yarn workspaces run lint:js
        yarn workspaces run lint:css

    - name: Lint PHP
      run: |
        BASE_REF=${{ github.base_ref }} php .github/bin/phpcs-branch.php 
